# This is a file that will install dependencies etc.

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "filehandling"
version = "0.1.1"

[tool.pytest.ini_options]
testpaths = ["tests"]
